export const CharactersImage = [
  { name: "Luke Skywalker", url: "https://swapi.dev/api/people/1/", src: "/assets/imgs/characters/LukeSkywalker.jpg" },
  { name: "C-3PO", url: "https://swapi.dev/api/people/2/", src: "/assets/imgs/characters/C-3PO.jpeg" },
  { name: "R2-D2", url: "https://swapi.dev/api/people/3/", src: "/assets/imgs/characters/R2-D2.jpg" },
  { name: "Darth Vader", url: "https://swapi.dev/api/people/4/", src: "/assets/imgs/characters/DarthVader.jpg" },
  { name: "Leia Organa", url: "https://swapi.dev/api/people/5/", src: "/assets/imgs/characters/LeiaOrgana.jpg" },
  { name: "Owen Lars", url: "https://swapi.dev/api/people/6/", src: "/assets/imgs/characters/OwenLars.jpg" },
  { name: "Beru Whitesun lars", url: "https://swapi.dev/api/people/7/", src: "/assets/imgs/characters/BeruWhitesunlars.jpg" },
  { name: "R5-D4", url: "https://swapi.dev/api/people/8/", src: "/assets/imgs/characters/R5-D4.jpg" },
  { name: "Biggs Darklighter", url: "https://swapi.dev/api/people/9/", src: "/assets/imgs/characters/BiggsDarklighter.jpeg" },
  { name: "Obi-Wan Kenobi", url: "https://swapi.dev/api/people/10/", src: "/assets/imgs/characters/Obi-WanKenobi.jpeg" },
  { name: "Anakin Skywalker", url: "https://swapi.dev/api/people/11/", src: "/assets/imgs/characters/AnakinSkywalker.jpg" },
  { name: "Wilhuff Tarkin", url: "https://swapi.dev/api/people/12/", src: "/assets/imgs/characters/WilhuffTarkin.jpg" },
  { name: "Chewbacca", url: "https://swapi.dev/api/people/13/", src: "/assets/imgs/characters/Chewbacca.jpg" },
  { name: "Han Solo", url: "https://swapi.dev/api/people/14/", src: "/assets/imgs/characters/HanSolo.jpg" },
  { name: "Greedo", url: "https://swapi.dev/api/people/15/", src: "/assets/imgs/characters/Greedo.jpeg" },
  { name: "Jabba Desilijic Tiure", url: "https://swapi.dev/api/people/16/", src: "/assets/imgs/characters/JabbaDesilijicTiure.jpg" },
  { name: "Unknown", url: "https://swapi.dev/api/people/17/", src: "/assets/imgs/characters/unkown" },
  { name: "Wedge Antilles", url: "https://swapi.dev/api/people/18/", src: "/assets/imgs/characters/WedgeAntilles.jpeg" },
  { name: "Jek Tono Porkins", url: "https://swapi.dev/api/people/19/", src: "/assets/imgs/characters/JekTonoPorkins.jpgg" },
  { name: "Yoda", url: "https://swapi.dev/api/people/20/", src: "/assets/imgs/characters/Yoda.jpeg" },
]
